### ISSUE TITLE
RPM distros have wrong dependencies in spec file

### ISSUE THREAD

**Issue by samnazarko** [samnazarko/osmc#76]

**Comment by malkavi** [comment]
For OpenSUSE dependencies you can search at "http://software.opensuse.org/132/es"
or **remove all the "Requires:" and the system will (have to) automatically find dependencies,**
(see: https://en.opensuse.org/openSUSE:Specfile_guidelines#Requires )
or maybe use something like:
Requires: pkgconfig(libjpeg)
instead of
Requires: libjpeg8
