### ISSUE TITLE
WiFi not working

### ISSUE THREAD

**Issue by roblan** [samnazarko/osmc#84]
Version : OSMC ALPHA3
Hardware : Raspberry Pi B with rtl8188eu

There is no WiFi connection...

**Comment by samnazarko** [comment]
Please try with Alpha 4 and let us know if this issue persists.

Alpha 4 release is imminent

**Comment by roblan** [comment]
Still no network connection.
But I've done some testing and it seems that a space in ssid seems to be the problem here.

**Comment by DBMandrake** [comment]
I can confirm that Alpha 4 was not able to connect to an SSID with a space in the name due to a string handling oversight in the preseed script.

I've fixed this and confirmed that I can now connect to a wireless network with spaces in the name and/or Passphrase.

To get this fix please temporarily connect via Ethernet, check for updates in the OSMC Settings addon and you should receive an updated version of the 'ftr-osmc' package.

You can verify you have the updated version by running the console/ssh command 'dpkg -l | grep osmc' - this will list the version of all installed osmc packages, you should now have version 1.2.1 or later of ftr-osmc.

Because the preseed script normally only runs once on first boot after install, you will need to run it manually to set up your wireless connection. To do so plug in your wireless adaptor and unplug your Ethernet cable, exit from kodi and press ESC to log in at the console. Then run:

sudo /usr/bin/preseed

Then wait until it completes which will take about 30 seconds. You can check to see how it went by checking the system journal afterwards with 'sudo journalctl' then look near the end of the log for lines with preseed in them.

Please let us know whether this fix allows you to connect to your network with a space in the name.

**Comment by roblan** [comment]
Fix worked - now there is no problem with connection.

But it seems to disconnect after AirPlay?

here is journalctl
http://paste.osmc.io/yipikutizi

**Comment by andrebower** [comment]
Cant get wifi with EDIMAX EW-7811UN on alpha 4

**Comment by andrebower** [comment]
Okay i did a reinstall with the stick plugged in. Now it is constantly glowing blue, not blinking. I can still not ssh into osmc.

**Comment by DBMandrake** [comment]
There isn't currently a working kernel driver in OSMC for the EW-7811UN. (I also have an EW-7811UTC and it is not detected)

It's on the list of devices we will try to support however.

**Comment by HenrikNyberg** [comment]
I get this problem in dmesg:
rtl8192c_common:rtl92c_fill_h2c_cmd(): return H2C cmd because of Fw download fail!!!
with alpha 4 with all available updates.

**Comment by samnazarko** [comment]
WiFi stability is much improved. Please re-open if persistent.

**Comment by HenrikNyberg** [comment]
I have now tried the newest version and is still having problem. I have tried alpha 4 with all updates and I have tried OSMC_TGT_rbp1_20150308.img.gz. Still have the same problem. I have gone back to raspbmc where it works perfectly and I get this registrated in dmesg usbcore: registered new interface driver rtl8192cu.

**Comment by LissieTilbrook** [comment]
And this issue is still persistent on the latest osmc.

I'm switching to LibreELEC. At least WiFi works there.

**Comment by samnazarko** [comment]
You've replied to a GitHub issue that's over three and a half years old. 
It's unclear which issue you are referring to. 

If you would like help with your WiFi connection, please start a forum post a discourse.osmc.tv.
